name: Python Test Workflow

on:
  push:
    paths:
      - requirements.txt
      - '**/*.py'  # Pythonファイルが変更されたときも実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  requirements_install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 必要に応じて変更

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          # pytestを使う場合の例
          pytest tests/  # テストファイルが tests/ ディレクトリにある前提
